shop-plugins:
  ShopGUIPlus: true
  Essentials: true
  EconomyShopGUI: true
  CMI: true
  ExcellentShop: true

currency-plugin:
  plugin: Vault
  # this value is only used when the plugin supports multiple currencies
  currency: ""

currency-plugins:
  CoinsEngine:
    register: true
    # CoinsEngine supports multiple currencies, so you can also add multiple here
    # "coins" is the name of the currency
    coins:
      tax: 0
      display:
        raw: "CoinsEngine-coins"
        gui: "&f%price% &#AAFFFFcoins"
        item:
          material: GOLD_INGOT
          name: "&#00DDFFCoinsEngine coins"
          lore:
            - " "
            - "&#00DDFF&l(!) &#00DDFFClick here to select!"